change type of options from `args` to `string`
spacetelescope/ci_watson pull request #63
Opened 2023-12-19 15:19 UTC by zacharyburnett

2023-12-19 15:50 UTC, zacharyburnett commented
downstream usages:
https://github.com/spacetelescope/drizzlepac/pull/1715
https://github.com/spacetelescope/jwst/pull/8149
https://github.com/spacetelescope/romancal/pull/1056

2023-12-19 16:30 UTC, pllim requested changes
Why is this needed, especially if it is going to break existing usages?

2023-12-21 14:57 UTC, pllim commented
Sure, but then all the downstream packages will need to do a version check of ci-watson and handle stuff accordingly. I just don't see the point. What was the motivation for this?

2023-12-21 15:08 UTC, zacharyburnett commented
the JWST regression test jobs were failing at the results parsing stage, because they couldn't correctly parse `inputs_root` and `results_root`; however, it looks like this was solved by a PR to `jenkins_shared_ci_utils`:
- https://github.com/spacetelescope/jenkins_shared_ci_utils/pull/89

You're right, it might be more headache to fix this than it's worth. I'll close this

2023-12-21 15:08 UTC, closed without merging